/*
 * Visier Object Configuration APIs
 * Visier APIs for managing objects in studio experience
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ConceptConfigurationResultDTO
 */
public class ConceptConfigurationResultDTOTest {
    private final ConceptConfigurationResultDTO model = new ConceptConfigurationResultDTO();

    /**
     * Model tests for ConceptConfigurationResultDTO
     */
    @Test
    public void testConceptConfigurationResultDTO() {
        // TODO: test ConceptConfigurationResultDTO
    }

    /**
     * Test the property 'conceptId'
     */
    @Test
    public void conceptIdTest() {
        // TODO: test conceptId
    }

    /**
     * Test the property 'projectId'
     */
    @Test
    public void projectIdTest() {
        // TODO: test projectId
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

}
