/*
 * Visier Object Configuration APIs
 * Visier APIs for managing objects in studio experience
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AnalyticObjectFilterDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PerspectiveNodeDTO
 */
public class PerspectiveNodeDTOTest {
    private final PerspectiveNodeDTO model = new PerspectiveNodeDTO();

    /**
     * Model tests for PerspectiveNodeDTO
     */
    @Test
    public void testPerspectiveNodeDTO() {
        // TODO: test PerspectiveNodeDTO
    }

    /**
     * Test the property 'selectionConceptUuid'
     */
    @Test
    public void selectionConceptUuidTest() {
        // TODO: test selectionConceptUuid
    }

    /**
     * Test the property 'symbolName'
     */
    @Test
    public void symbolNameTest() {
        // TODO: test symbolName
    }

    /**
     * Test the property 'analyticObjectFilters'
     */
    @Test
    public void analyticObjectFiltersTest() {
        // TODO: test analyticObjectFilters
    }

}
