/*
 * Visier Object Configuration APIs
 * Visier APIs for managing objects in studio experience
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PerspectiveNodeDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PerspectiveConfigurationDTO
 */
public class PerspectiveConfigurationDTOTest {
    private final PerspectiveConfigurationDTO model = new PerspectiveConfigurationDTO();

    /**
     * Model tests for PerspectiveConfigurationDTO
     */
    @Test
    public void testPerspectiveConfigurationDTO() {
        // TODO: test PerspectiveConfigurationDTO
    }

    /**
     * Test the property 'perspectiveId'
     */
    @Test
    public void perspectiveIdTest() {
        // TODO: test perspectiveId
    }

    /**
     * Test the property 'perspectiveName'
     */
    @Test
    public void perspectiveNameTest() {
        // TODO: test perspectiveName
    }

    /**
     * Test the property 'perspectiveNodes'
     */
    @Test
    public void perspectiveNodesTest() {
        // TODO: test perspectiveNodes
    }

}
