/*
 * Visier Object Configuration APIs
 * Visier APIs for managing objects in studio experience
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.DimensionMemberDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * DimensionFilterDTO
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class DimensionFilterDTO {
  public static final String SERIALIZED_NAME_DIMENSION_ID = "dimensionId";
  @SerializedName(SERIALIZED_NAME_DIMENSION_ID)
  private String dimensionId;

  public static final String SERIALIZED_NAME_SYMBOL_NAME = "symbolName";
  @SerializedName(SERIALIZED_NAME_SYMBOL_NAME)
  private String symbolName;

  public static final String SERIALIZED_NAME_DIMENSION_MEMBERS = "dimensionMembers";
  @SerializedName(SERIALIZED_NAME_DIMENSION_MEMBERS)
  private List<DimensionMemberDTO> dimensionMembers = null;

  public DimensionFilterDTO() {
  }

  public DimensionFilterDTO dimensionId(String dimensionId) {
    
    
    
    
    this.dimensionId = dimensionId;
    return this;
  }

   /**
   * The UUID of the dimension.
   * @return dimensionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The UUID of the dimension.")

  public String getDimensionId() {
    return dimensionId;
  }


  public void setDimensionId(String dimensionId) {
    
    
    
    this.dimensionId = dimensionId;
  }


  public DimensionFilterDTO symbolName(String symbolName) {
    
    
    
    
    this.symbolName = symbolName;
    return this;
  }

   /**
   * The symbol name of the dimension.
   * @return symbolName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The symbol name of the dimension.")

  public String getSymbolName() {
    return symbolName;
  }


  public void setSymbolName(String symbolName) {
    
    
    
    this.symbolName = symbolName;
  }


  public DimensionFilterDTO dimensionMembers(List<DimensionMemberDTO> dimensionMembers) {
    
    
    
    
    this.dimensionMembers = dimensionMembers;
    return this;
  }

  public DimensionFilterDTO addDimensionMembersItem(DimensionMemberDTO dimensionMembersItem) {
    if (this.dimensionMembers == null) {
      this.dimensionMembers = new ArrayList<>();
    }
    this.dimensionMembers.add(dimensionMembersItem);
    return this;
  }

   /**
   * A list of dimension members to map to the perspective node.   Note: If this array is empty, all dimension members will be removed for the node.
   * @return dimensionMembers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of dimension members to map to the perspective node.   Note: If this array is empty, all dimension members will be removed for the node.")

  public List<DimensionMemberDTO> getDimensionMembers() {
    return dimensionMembers;
  }


  public void setDimensionMembers(List<DimensionMemberDTO> dimensionMembers) {
    
    
    
    this.dimensionMembers = dimensionMembers;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the DimensionFilterDTO instance itself
   */
  public DimensionFilterDTO putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DimensionFilterDTO dimensionFilterDTO = (DimensionFilterDTO) o;
    return Objects.equals(this.dimensionId, dimensionFilterDTO.dimensionId) &&
        Objects.equals(this.symbolName, dimensionFilterDTO.symbolName) &&
        Objects.equals(this.dimensionMembers, dimensionFilterDTO.dimensionMembers)&&
        Objects.equals(this.additionalProperties, dimensionFilterDTO.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dimensionId, symbolName, dimensionMembers, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DimensionFilterDTO {\n");
    sb.append("    dimensionId: ").append(toIndentedString(dimensionId)).append("\n");
    sb.append("    symbolName: ").append(toIndentedString(symbolName)).append("\n");
    sb.append("    dimensionMembers: ").append(toIndentedString(dimensionMembers)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("dimensionId");
    openapiFields.add("symbolName");
    openapiFields.add("dimensionMembers");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to DimensionFilterDTO
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!DimensionFilterDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DimensionFilterDTO is not found in the empty JSON string", DimensionFilterDTO.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("dimensionId") != null && !jsonObj.get("dimensionId").isJsonNull()) && !jsonObj.get("dimensionId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dimensionId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dimensionId").toString()));
      }
      if ((jsonObj.get("symbolName") != null && !jsonObj.get("symbolName").isJsonNull()) && !jsonObj.get("symbolName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `symbolName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("symbolName").toString()));
      }
      if (jsonObj.get("dimensionMembers") != null && !jsonObj.get("dimensionMembers").isJsonNull()) {
        JsonArray jsonArraydimensionMembers = jsonObj.getAsJsonArray("dimensionMembers");
        if (jsonArraydimensionMembers != null) {
          // ensure the json data is an array
          if (!jsonObj.get("dimensionMembers").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `dimensionMembers` to be an array in the JSON string but got `%s`", jsonObj.get("dimensionMembers").toString()));
          }

          // validate the optional field `dimensionMembers` (array)
          for (int i = 0; i < jsonArraydimensionMembers.size(); i++) {
            DimensionMemberDTO.validateJsonObject(jsonArraydimensionMembers.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DimensionFilterDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DimensionFilterDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DimensionFilterDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DimensionFilterDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<DimensionFilterDTO>() {
           @Override
           public void write(JsonWriter out, DimensionFilterDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public DimensionFilterDTO read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             DimensionFilterDTO instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of DimensionFilterDTO given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of DimensionFilterDTO
  * @throws IOException if the JSON string is invalid with respect to DimensionFilterDTO
  */
  public static DimensionFilterDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DimensionFilterDTO.class);
  }

 /**
  * Convert an instance of DimensionFilterDTO to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

