/*
 * Visier Object Configuration APIs
 * Visier APIs for managing objects in studio experience
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PerspectiveNodeDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * PerspectiveConfigurationDTO
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PerspectiveConfigurationDTO {
  public static final String SERIALIZED_NAME_PERSPECTIVE_ID = "perspectiveId";
  @SerializedName(SERIALIZED_NAME_PERSPECTIVE_ID)
  private String perspectiveId;

  public static final String SERIALIZED_NAME_PERSPECTIVE_NAME = "perspectiveName";
  @SerializedName(SERIALIZED_NAME_PERSPECTIVE_NAME)
  private String perspectiveName;

  public static final String SERIALIZED_NAME_PERSPECTIVE_NODES = "perspectiveNodes";
  @SerializedName(SERIALIZED_NAME_PERSPECTIVE_NODES)
  private List<PerspectiveNodeDTO> perspectiveNodes = null;

  public PerspectiveConfigurationDTO() {
  }

  public PerspectiveConfigurationDTO perspectiveId(String perspectiveId) {
    
    
    
    
    this.perspectiveId = perspectiveId;
    return this;
  }

   /**
   * The UUID of the perspective.
   * @return perspectiveId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The UUID of the perspective.")

  public String getPerspectiveId() {
    return perspectiveId;
  }


  public void setPerspectiveId(String perspectiveId) {
    
    
    
    this.perspectiveId = perspectiveId;
  }


  public PerspectiveConfigurationDTO perspectiveName(String perspectiveName) {
    
    
    
    
    this.perspectiveName = perspectiveName;
    return this;
  }

   /**
   * The display name of the perspective.
   * @return perspectiveName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The display name of the perspective.")

  public String getPerspectiveName() {
    return perspectiveName;
  }


  public void setPerspectiveName(String perspectiveName) {
    
    
    
    this.perspectiveName = perspectiveName;
  }


  public PerspectiveConfigurationDTO perspectiveNodes(List<PerspectiveNodeDTO> perspectiveNodes) {
    
    
    
    
    this.perspectiveNodes = perspectiveNodes;
    return this;
  }

  public PerspectiveConfigurationDTO addPerspectiveNodesItem(PerspectiveNodeDTO perspectiveNodesItem) {
    if (this.perspectiveNodes == null) {
      this.perspectiveNodes = new ArrayList<>();
    }
    this.perspectiveNodes.add(perspectiveNodesItem);
    return this;
  }

   /**
   * A list of nodes in the perspective.
   * @return perspectiveNodes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of nodes in the perspective.")

  public List<PerspectiveNodeDTO> getPerspectiveNodes() {
    return perspectiveNodes;
  }


  public void setPerspectiveNodes(List<PerspectiveNodeDTO> perspectiveNodes) {
    
    
    
    this.perspectiveNodes = perspectiveNodes;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PerspectiveConfigurationDTO instance itself
   */
  public PerspectiveConfigurationDTO putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PerspectiveConfigurationDTO perspectiveConfigurationDTO = (PerspectiveConfigurationDTO) o;
    return Objects.equals(this.perspectiveId, perspectiveConfigurationDTO.perspectiveId) &&
        Objects.equals(this.perspectiveName, perspectiveConfigurationDTO.perspectiveName) &&
        Objects.equals(this.perspectiveNodes, perspectiveConfigurationDTO.perspectiveNodes)&&
        Objects.equals(this.additionalProperties, perspectiveConfigurationDTO.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(perspectiveId, perspectiveName, perspectiveNodes, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PerspectiveConfigurationDTO {\n");
    sb.append("    perspectiveId: ").append(toIndentedString(perspectiveId)).append("\n");
    sb.append("    perspectiveName: ").append(toIndentedString(perspectiveName)).append("\n");
    sb.append("    perspectiveNodes: ").append(toIndentedString(perspectiveNodes)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("perspectiveId");
    openapiFields.add("perspectiveName");
    openapiFields.add("perspectiveNodes");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PerspectiveConfigurationDTO
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PerspectiveConfigurationDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PerspectiveConfigurationDTO is not found in the empty JSON string", PerspectiveConfigurationDTO.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("perspectiveId") != null && !jsonObj.get("perspectiveId").isJsonNull()) && !jsonObj.get("perspectiveId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `perspectiveId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("perspectiveId").toString()));
      }
      if ((jsonObj.get("perspectiveName") != null && !jsonObj.get("perspectiveName").isJsonNull()) && !jsonObj.get("perspectiveName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `perspectiveName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("perspectiveName").toString()));
      }
      if (jsonObj.get("perspectiveNodes") != null && !jsonObj.get("perspectiveNodes").isJsonNull()) {
        JsonArray jsonArrayperspectiveNodes = jsonObj.getAsJsonArray("perspectiveNodes");
        if (jsonArrayperspectiveNodes != null) {
          // ensure the json data is an array
          if (!jsonObj.get("perspectiveNodes").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `perspectiveNodes` to be an array in the JSON string but got `%s`", jsonObj.get("perspectiveNodes").toString()));
          }

          // validate the optional field `perspectiveNodes` (array)
          for (int i = 0; i < jsonArrayperspectiveNodes.size(); i++) {
            PerspectiveNodeDTO.validateJsonObject(jsonArrayperspectiveNodes.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PerspectiveConfigurationDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PerspectiveConfigurationDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PerspectiveConfigurationDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PerspectiveConfigurationDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<PerspectiveConfigurationDTO>() {
           @Override
           public void write(JsonWriter out, PerspectiveConfigurationDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PerspectiveConfigurationDTO read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PerspectiveConfigurationDTO instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PerspectiveConfigurationDTO given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PerspectiveConfigurationDTO
  * @throws IOException if the JSON string is invalid with respect to PerspectiveConfigurationDTO
  */
  public static PerspectiveConfigurationDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PerspectiveConfigurationDTO.class);
  }

 /**
  * Convert an instance of PerspectiveConfigurationDTO to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

