/*
 * Visier Object Configuration APIs
 * Visier APIs for managing objects in studio experience
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AnalyticObjectFilterDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * PerspectiveNodeDTO
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PerspectiveNodeDTO {
  public static final String SERIALIZED_NAME_SELECTION_CONCEPT_UUID = "selectionConceptUuid";
  @SerializedName(SERIALIZED_NAME_SELECTION_CONCEPT_UUID)
  private String selectionConceptUuid;

  public static final String SERIALIZED_NAME_SYMBOL_NAME = "symbolName";
  @SerializedName(SERIALIZED_NAME_SYMBOL_NAME)
  private String symbolName;

  public static final String SERIALIZED_NAME_ANALYTIC_OBJECT_FILTERS = "analyticObjectFilters";
  @SerializedName(SERIALIZED_NAME_ANALYTIC_OBJECT_FILTERS)
  private List<AnalyticObjectFilterDTO> analyticObjectFilters = null;

  public PerspectiveNodeDTO() {
  }

  public PerspectiveNodeDTO selectionConceptUuid(String selectionConceptUuid) {
    
    
    
    
    this.selectionConceptUuid = selectionConceptUuid;
    return this;
  }

   /**
   * The UUID of the node&#39;s selection concept. Perspective nodes are generated as selection concepts to enable filtering.
   * @return selectionConceptUuid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The UUID of the node's selection concept. Perspective nodes are generated as selection concepts to enable filtering.")

  public String getSelectionConceptUuid() {
    return selectionConceptUuid;
  }


  public void setSelectionConceptUuid(String selectionConceptUuid) {
    
    
    
    this.selectionConceptUuid = selectionConceptUuid;
  }


  public PerspectiveNodeDTO symbolName(String symbolName) {
    
    
    
    
    this.symbolName = symbolName;
    return this;
  }

   /**
   * The symbol name of the selection concept. For example, \&quot;isExitActualSystemTermination\&quot;.
   * @return symbolName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The symbol name of the selection concept. For example, \"isExitActualSystemTermination\".")

  public String getSymbolName() {
    return symbolName;
  }


  public void setSymbolName(String symbolName) {
    
    
    
    this.symbolName = symbolName;
  }


  public PerspectiveNodeDTO analyticObjectFilters(List<AnalyticObjectFilterDTO> analyticObjectFilters) {
    
    
    
    
    this.analyticObjectFilters = analyticObjectFilters;
    return this;
  }

  public PerspectiveNodeDTO addAnalyticObjectFiltersItem(AnalyticObjectFilterDTO analyticObjectFiltersItem) {
    if (this.analyticObjectFilters == null) {
      this.analyticObjectFilters = new ArrayList<>();
    }
    this.analyticObjectFilters.add(analyticObjectFiltersItem);
    return this;
  }

   /**
   * A list of analytic object filters indicating the analytic object and dimensions used for the selection concept.
   * @return analyticObjectFilters
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of analytic object filters indicating the analytic object and dimensions used for the selection concept.")

  public List<AnalyticObjectFilterDTO> getAnalyticObjectFilters() {
    return analyticObjectFilters;
  }


  public void setAnalyticObjectFilters(List<AnalyticObjectFilterDTO> analyticObjectFilters) {
    
    
    
    this.analyticObjectFilters = analyticObjectFilters;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PerspectiveNodeDTO instance itself
   */
  public PerspectiveNodeDTO putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PerspectiveNodeDTO perspectiveNodeDTO = (PerspectiveNodeDTO) o;
    return Objects.equals(this.selectionConceptUuid, perspectiveNodeDTO.selectionConceptUuid) &&
        Objects.equals(this.symbolName, perspectiveNodeDTO.symbolName) &&
        Objects.equals(this.analyticObjectFilters, perspectiveNodeDTO.analyticObjectFilters)&&
        Objects.equals(this.additionalProperties, perspectiveNodeDTO.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(selectionConceptUuid, symbolName, analyticObjectFilters, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PerspectiveNodeDTO {\n");
    sb.append("    selectionConceptUuid: ").append(toIndentedString(selectionConceptUuid)).append("\n");
    sb.append("    symbolName: ").append(toIndentedString(symbolName)).append("\n");
    sb.append("    analyticObjectFilters: ").append(toIndentedString(analyticObjectFilters)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("selectionConceptUuid");
    openapiFields.add("symbolName");
    openapiFields.add("analyticObjectFilters");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PerspectiveNodeDTO
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PerspectiveNodeDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PerspectiveNodeDTO is not found in the empty JSON string", PerspectiveNodeDTO.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("selectionConceptUuid") != null && !jsonObj.get("selectionConceptUuid").isJsonNull()) && !jsonObj.get("selectionConceptUuid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `selectionConceptUuid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("selectionConceptUuid").toString()));
      }
      if ((jsonObj.get("symbolName") != null && !jsonObj.get("symbolName").isJsonNull()) && !jsonObj.get("symbolName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `symbolName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("symbolName").toString()));
      }
      if (jsonObj.get("analyticObjectFilters") != null && !jsonObj.get("analyticObjectFilters").isJsonNull()) {
        JsonArray jsonArrayanalyticObjectFilters = jsonObj.getAsJsonArray("analyticObjectFilters");
        if (jsonArrayanalyticObjectFilters != null) {
          // ensure the json data is an array
          if (!jsonObj.get("analyticObjectFilters").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `analyticObjectFilters` to be an array in the JSON string but got `%s`", jsonObj.get("analyticObjectFilters").toString()));
          }

          // validate the optional field `analyticObjectFilters` (array)
          for (int i = 0; i < jsonArrayanalyticObjectFilters.size(); i++) {
            AnalyticObjectFilterDTO.validateJsonObject(jsonArrayanalyticObjectFilters.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PerspectiveNodeDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PerspectiveNodeDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PerspectiveNodeDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PerspectiveNodeDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<PerspectiveNodeDTO>() {
           @Override
           public void write(JsonWriter out, PerspectiveNodeDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PerspectiveNodeDTO read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PerspectiveNodeDTO instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PerspectiveNodeDTO given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PerspectiveNodeDTO
  * @throws IOException if the JSON string is invalid with respect to PerspectiveNodeDTO
  */
  public static PerspectiveNodeDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PerspectiveNodeDTO.class);
  }

 /**
  * Convert an instance of PerspectiveNodeDTO to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

